from django.urls import path
from django.contrib.auth.views import LogoutView
from events.views import (
    SignUpView, CustomLoginView, ActivateView, DashboardRedirectView, 
    AdminDashboardView, OrganizerDashboardView, ParticipantDashboardView, 
    DashboardView, RSVPEventView, MyRSVPsView, ManageRSVPsView, 
    EventRSVPsView, DeleteRSVPView, HomeView, EventsView, ContactView, 
    EventDetailView, EventCreateView, EventUpdateView, EventDeleteView, 
    ParticipantCreateView, ParticipantUpdateView, ParticipantDeleteView, 
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, 
    RBACDashboardView, AssignUserRoleView, CreateGroupView, 
    DeleteGroupView, DeleteUserView
)

urlpatterns = [
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('sign-in/', CustomLoginView.as_view(), name='sign-in'),
    path('sign-out/', LogoutView.as_view(next_page='/sign-in/'), name='sign-out'),
    path('activate/<int:user_id>/<str:token>/', ActivateView.as_view(), name='activate'),
    path('dashboard/redirect/', DashboardRedirectView.as_view(), name='dashboard-redirect'),
    path('dashboard/admin/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('dashboard/organizer/', OrganizerDashboardView.as_view(), name='organizer-dashboard'),
    path('dashboard/participant/', ParticipantDashboardView.as_view(), name='participant-dashboard'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('events/<int:event_id>/rsvp/', RSVPEventView.as_view(), name='rsvp-event'),
    path('my-rsvps/', MyRSVPsView.as_view(), name='my-rsvps'),
    path('manage-rsvps/', ManageRSVPsView.as_view(), name='manage-rsvps'),
    path('events/<int:event_id>/rsvps/', EventRSVPsView.as_view(), name='event-rsvps'),
    path('rsvps/<int:rsvp_id>/delete/', DeleteRSVPView.as_view(), name='delete-rsvp'),
    path('', HomeView.as_view(), name='home'),
    path('events/', EventsView.as_view(), name='events'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-detail'),
    path('event/add/', EventCreateView.as_view(), name='event-add'),
    path('event/<int:pk>/edit/', EventUpdateView.as_view(), name='event-edit'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete'),
    path('participant/add/', ParticipantCreateView.as_view(), name='participant-add'),
    path('participant/<int:pk>/edit/', ParticipantUpdateView.as_view(), name='participant-edit'),
    path('participant/<int:pk>/delete/', ParticipantDeleteView.as_view(), name='participant-delete'),
    path('category/add/', CategoryCreateView.as_view(), name='category-add'),
    path('category/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category-edit'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('rbac/', RBACDashboardView.as_view(), name='rbac-dashboard'),
    path('rbac/assign-role/<int:user_id>/', AssignUserRoleView.as_view(), name='assign-role'),
    path('rbac/create-group/', CreateGroupView.as_view(), name='create-group'),
    path('rbac/delete-group/<int:group_id>/', DeleteGroupView.as_view(), name='delete-group'),
    path('rbac/delete-user/<int:user_id>/', DeleteUserView.as_view(), name='delete-user'),
]
